### ISSUE TITLE
No result from this JSON file at www.paris-streetart.com

### ISSUE THREAD

**Issue by IanHopkinson** [scraperwiki/geojson-tool#3]
This JSON appears not to be parsable - I can't see any error messages...
http://www.paris-streetart.com/test/map.geojson

**Comment by drj11** [comment]
Now we get an error message (which is good).

However, the GeoJSON is valid (as far as i can tell), so the tool should cope with it.

It turns out that the problem is that the feature has a `id` key, and it also has, in the `properties` sub-object, an `ID` key. The GeoJSON tool adds the `id` key to the `properties` dict internally, and when saved to the `scraperwiki` datastore the two keys that differ only in case conflict.

Even if the tool didn't do this `id` thing there is the possibility of a conflict because we might have a GeoJSON object with properties that differ only in case, eg `description` and `Description`.

So we need to cope with keys that conflict anyway.
